title: Nivaldo Melo # Shown in header on pages with full_logo: true
short_logo: N. M. # Shown in header on all pages by default unless full_logo: true is set
description: > # The description for your site
  A personal website/blog
baseurl: "/" # The subpath of your site, e.g. /blog/
url: "https://nivaldogmelo.github.io" # The base hostname & protocol for your site

author:
  name: Nivaldo Melo
  github: nivaldogmelo # GitHub username, used for GitHub icon on the top right
  linkedin: nivaldogmelo # Your LinkedIn profile url name, used for LinkedIn icon on the top right
  email: nivaldogmelo@gmail.com # Used for email icon on the top right
  homepage: https://nivaldogmelo.github.io # This links to your name in post meta

disqus_name: # Setting this will turn on Disqus comments
g_track_id: G-DBYYP58X18 # Google Analytics tracking ID (e.g. UA-000000-2), setting this will turn on Google Analytics

markdown: kramdown

defaults: # Recommended defaults, you may set your own
  -
    scope:
      path: _posts
    values:
      comments: true
  -
    scope:
      path: pages/redirects
    values:
      layout: redirect
      index: false
      listed: false
  -
    scope:
      path: pages/tags
    values:
      layout: tag
      sitemap:
        priority: 0.4
