baseURL = "https://nivaldogmelo.github.io"
title = "nivaldogmelo"
theme = "hugo-coder"
languageCode = "en"
defaultcontentlanguage = "en"
enableEmoji = true

[pagination]
pagerSize = 20

[params]
author = "Nivaldo"
info = "I'm a DevOps Engineer, which likes develop in Rust whenever I get time"
description = "Nivaldo's personal website"
keywords = "blog,developer,personal"
avatarurl = "images/avatar.jpg"
#gravatar = "john.doe@example.com"
favicon_32 = "/img/favicon-32x32.png"
favicon_16 = "/img/favicon-16x16.png"
since = 2019

colorScheme = "auto"
hidecolorschemetoggle = false

customCSS = ["css/custom.css"]
customSCSS = []
customJS = []

[markup.highlight]
style = "dracula"

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

# Social links
[[params.social]]
name = "Github"
# icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/nivaldogmelo/"

[[params.social]]
name = "LinkedIn"
# icon = "fa-brands fa-2x fa-linkedin"
weight = 2
url = "https://www.linkedin.com/in/nivaldogmelo/"

[[params.social]]
name = "Medium"
# icon = "fa-brands fa-2x fa-medium"
weight = 3
url = "https://medium.com/@nivaldogmelo"

[[params.social]]
name = "RSS"
# icon = "fa-solid fa-rss-square fa-2x"
weight = 4
url = "/posts/index.xml"

[languages.en]
languageName = ":us:"

# Menu links
[[languages.en.menu.main]]
  name = "About"
  weight = 1
  url  = "about/"

[[languages.en.menu.main]]
  name = "Blog"
  weight = 2
  url  = "posts/"

[[languages.en.menu.main]]
  name = "Projects"
  weight = 3
  url  = "projects/"

[languages.pt-br]
languageName = ":brazil:"
title = "nivaldogmelo"

[languages.pt-br.params]
author = "Nivaldo"
info = "Sou um engenheiro DevOps, que gosta de desenvoler em Rust sempre que consigo"
description = "Site pessoal de Nivaldo"
keywords = "blog,desenvolvedor,pessoal"

[[languages.pt-br.menu.main]]
name = "Sobre"
weight = 1
url = "about/"

[[languages.pt-br.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.pt-br.menu.main]]
name = "Projetos"
weight = 3
url = "projects/"