baseURL = "https://nivaldogmelo.github.io"
title = "nivaldogmelo"
theme = "hugo-coder"
languageCode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


[params]
  author = "Nivaldo Melo"
  info = "SRE, Golang dev and big fan of sitcoms"
  description = "Nivaldo's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"
  #gravatar = "john.doe@example.com"

  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2019

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  customCSS = ["css/custom.css"]
  customSCSS = []
  customJS = []

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/nivaldogmelo/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 4
url = "https://www.linkedin.com/in/nivaldogmelo/"

[[params.social]]
name = "Medium"
icon = "fa fa-2x fa-medium"
weight = 5
url = "https://medium.com/@nivaldogmelo"

[languages.en]
languageName = ":uk:"

# Menu links
[[languages.en.menu.main]]
  name = "About"
  weight = 1
  url  = "about/"

[[languages.en.menu.main]]
  name = "Blog"
  weight = 2
  url  = "posts/"

[languages.pt-br]
languageName = ":brazil:"
title = "nivaldogmelo"

[languages.pt-br.params]
author = "Nivaldo Melo"
info = "SRE, Desenvolvedor Golang e um grande fã de sitcoms"
description = "Site pessoal de Nivaldo"
keywords = "blog,desenvolvedor,pessoal"

[[languages.pt-br.menu.main]]
name = "Sobre"
weight = 1
url = "about/"

[[languages.pt-br.menu.main]]
name = "Blog"
weight = 2
url = "posts/"
